name: Checks

on: [ pull_request, push ]

jobs:
  # Code formatting.
  fmt:
    name: cargo-fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo fmt --all -- --check

  prettier:
    name: Prettier
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - run: npm install -g pnpm
      - run: pnpm install
      - run: pnpm run format-check

  # Static analyzer.
  clippy:
    name: cargo-clippy
    runs-on: ubuntu-latest
    steps:
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf llvm-dev clang cmake grcov
          version: "1.0"  # bump this to invalidate the cache when needed

      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo clippy --all-targets --all-features -- -D warnings

  # Check links in the documentation.
  deadlinks:
    name: Deadlinks
    runs-on: ubuntu-latest
    steps:
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf llvm-dev clang cmake grcov
          version: "1.0"  # bump this to invalidate the cache when needed
          
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo install cargo-deadlinks
      - run: cargo doc --no-deps -p tauri-plugin-google-auth
      - run: cargo deadlinks --no-build

  # Check links in markdown files.
  mlc:
    name: MLC
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: becheran/mlc@v0.14.3

  # Spellcheck.
  spellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: streetsidesoftware/cspell-action@v1.0.1
        with:
          files: "**/*.{rs,md}"

  # Markdown formatting.
  markdown:
    name: Markdown lints
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: nosborn/github-action-markdown-cli@v1.1.1
        with:
          files: .

  # cargo-deny.
  deny:
    name: cargo-deny
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: EmbarkStudios/cargo-deny-action@v1

  # cargo-semver.
  semver:
    name: cargo-semver
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: obi1kenobi/cargo-semver-checks-action@v2

  